local Constants = {}
Constants.__index = Constants

------------------------------------------------------

-- Log levels
Constants.DEBUG = 1
Constants.INFO = 2
Constants.WARNING = 3
Constants.ERROR = 4

-- Tags
Constants.REGION = 'Region'
Constants.CUBE = 'Cube'
Constants.PROFICIENCY = 'Proficiency'
Constants.FORTIFICATION = 'Fortification'
Constants.FAVOR_TOKEN = 'FavorToken'
Constants.RAPPORT_TOKEN = 'RapportToken'
Constants.SCORING_MARKER = 'ScoringMarker'
Constants.PLAYER_MARKER = 'PlayerMarker'
Constants.JOURNEY_DECK = 'JourneyDeck'
Constants.SECRET_DECK = 'SecretDeck'
Constants.ENDGAME_DECK = 'EndgameDeck'
Constants.INSPIRATION_START_DECK = 'InspirationStartDeck'
Constants.INSPIRATION_DECK = 'InspirationDeck'
Constants.STRENGTH_START_DECK = 'StrengthStartDeck'
Constants.STRENGTH_DECK = 'StrengthDeck'
Constants.KNOWLEDGE_START_DECK = 'KnowledgeStartDeck'
Constants.KNOWLEDGE_DECK = 'KnowledgeDeck'
Constants.WISDOM_DECK = 'WisdomDeck'
Constants.COURAGE_DECK = 'CourageDeck'
Constants.VISION_DECK = 'VisionDeck'
Constants.PET_DECK = 'PetDeck'
Constants.LOOT_DECK = 'LootDeck'
Constants.TREACHERY = 'Treachery'

-- Players
Constants.WHITE = 'White'
Constants.PURPLE = 'Purple'
Constants.ORANGE = 'Orange'
Constants.GREEN = 'Green'
Constants.BLUE = 'Blue'

Constants.PLAYER_BOARDS = {
    [Constants.WHITE] = { board = '6f5c24', zone = '0d8581' },
    [Constants.PURPLE] = { board = '7a45c8', zone = '2d144a' },
    [Constants.ORANGE] = { board = '240cb9', zone = '9e1bfe' },
    [Constants.GREEN] = { board = 'a26ddd', zone = '07f377' },
    [Constants.BLUE] = { board = '8464ac', zone = '65bd2d' },
}

-- Attributes
Constants.STRENGTH = 'Strength'
Constants.KNOWLEDGE = 'Knowledge'
Constants.INSPIRATION = 'Inspiration'

Constants.VISION = 'Vision'
Constants.WISDOM = 'Wisdom'
Constants.COURAGE = 'Courage'

Constants.ATTRIBUTES_LIST = {Constants.STRENGTH, Constants.VISION, Constants.KNOWLEDGE, Constants.WISDOM, Constants.INSPIRATION, Constants.COURAGE}

Constants.ATTRIBUTE_ZONES = {
    [Constants.STRENGTH] = '6238a2',
    [Constants.KNOWLEDGE] = '80ce3f',
    [Constants.INSPIRATION] = 'e3a085',
    [Constants.VISION] = '6ea76e',
    [Constants.WISDOM] = 'dc7af6',
    [Constants.COURAGE] = '7ff704',
}

Constants.COLOR_PER_ATTRIBUTE = {
    [Constants.STRENGTH] = '#D22F2F',
    [Constants.KNOWLEDGE] = '#4D99C4',
    [Constants.INSPIRATION] = '#CFBB47',
    [Constants.VISION] = '#8543BD',
    [Constants.WISDOM] = '#6CC14A',
    [Constants.COURAGE] = '#C27B34',
}

Constants.MAIN_BOARD = '0a5552'
Constants.REGION_BAG = 'f3a4ef'
Constants.TRASH_BAG = 'cf6ca1'

Constants.BUTTON_COLOR = '#1d1d1dff'
Constants.BUTTON_COLORS = '#FFFFFF|#c2c2c2ff|#8f8f8fff|#c74040ff'
Constants.BUTTON_TEXT_COLOR = '#d8d8d8ff'

Constants.HIGHLIGHTED_BUTTON_COLOR = '#eeeeeeff'
Constants.HIGHLIGHTED_BUTTON_TEXT_COLOR = '#1d1d1dff'

Constants.TOGGLE_BUTTON_DESELECTED_COLOR = '#313131ff'
Constants.TOGGLE_BUTTON_DESELECTED_COLORS = Constants.TOGGLE_BUTTON_DESELECTED_COLOR .. '|#4e4e4eff|#8f8f8fff|#c74040ff'
Constants.TOGGLE_BUTTON_DESELECTED_TEXT_COLOR = '#d8d8d8ff'
Constants.TOGGLE_BUTTON_SELECTED_COLOR = '#f1f1f1ff'
Constants.TOGGLE_BUTTON_SELECTED_COLORS = Constants.TOGGLE_BUTTON_SELECTED_COLOR .. '|#ccccccff|#8f8f8fff|#c74040ff'
Constants.TOGGLE_BUTTON_SELECTED_TEXT_COLOR = '#313131ff'

------------------------------------------------------

return Constants
